### ISSUE TITLE
npm ERR! missing script: build

### ISSUE THREAD

**Issue by Ofer-Gal** [JeremyLikness/AngularES6HealthApp#1]
the line 
npm run-script build
does not work
Also 
npm run-script connect  errors with: npm ERR! missing script: connect

**Comment by Ofer-Gal** [comment]
Sorry to be a novice newbee but It does not work for me :-)
E:\GitHub\AngularES6HealthApp\AngularES6HealthApp> grunt build

> > Local Npm module "grunt-connect" not found. Is it installed?

Running "browserify:dist" (browserify) task

> > Bundle ./dist/app.js created.

Done, without errors.

E:\GitHub\AngularES6HealthApp\AngularES6HealthApp> grunt connect

> > Local Npm module "grunt-connect" not found. Is it installed?
> > Warning: Task "connect" not found. Use --force to continue.

Aborted due to warnings.

E:\GitHub\AngularES6HealthApp\AngularES6HealthApp> grunt connect --force

> > Local Npm module "grunt-connect" not found. Is it installed?
> > Warning: Task "connect" not found. Used --force, continuing.

Done, but with warnings.
what port now?

**Comment by JeremyLikness** [comment]
Good feedback. I had a "dirty" environment and there was a disconnect between the "-contrib" vs "-" versions. If you pull the updated package.json, npm install, it should work now - the correct package is "grunt-connect" not "grunt-contrib-connect" for the workflow here. Latest commit I believe will resolve this, let me know if it doesn't and I appreciatae your patience. It will show the port when you run it.

**Comment by Ofer-Gal** [comment]
Thank YOU for the patience :-) , It did run fine now and told me I am Overweight (Hate the truth :-))

**Comment by JeremyLikness** [comment]
Glad to hear it worked for you, and it was my pleasure. Sorry to hear the tool was so blunt. :)
